### ISSUE TITLE
Can't install extension in the latest update of VSCode

### ISSUE THREAD

**Issue by tom-madafa** [ivanesmantovich/halftone-theme-vsc#1]
Hello,

Really enjoy the minimal style of this theme. I tried to install it but got an error:
![image](https://github.com/ivanesmantovich/halftone-theme-vsc/assets/155396855/f2b4c8fb-782f-4d4d-8689-30703498fb71)

I am not sure why, maybe just some config issue. 

Cheers!

**Comment by ivanesmantovich** [comment]
I lowered the required VSCode version. Should be fixed now!
